### ISSUE TITLE
gradle-example-minimal does not publish

### ISSUE THREAD

**Issue by iNikem** [JFrogDev/project-examples#113]
I have cloned this repository, changed Artifactory server location and ran it. Nothing happens. `artifactoryPublish` task is noop: no pom file is generated, nothing is published, no error is reported.

**Comment by iNikem** [comment]
Guys, do you care to respond to bug reports?

**Comment by DimaNevelev** [comment]
@iNikem ,
I've just ran this example with Gradle 4.0.1 and 4.6 and everything worked.
Can you provide us more information about your environment, the Gradle version and logs?

**Comment by iNikem** [comment]
It seems that everything works just fine with latest version 4.7.0 of the plugin and fails with 4.6.2. So I will close this issue.
