### ISSUE TITLE
simplify bash scripts by taking the authentication out of them

### ISSUE THREAD

**Issue by ssbarnea** [JFrogDev/project-examples#13]
CURL can load credentials from `~/.netrc` and which means that by adding the `-n` parameter to the curl commands you can remove all the authentication part out of the scripts (which is also a security issue).

**Comment by denebeim** [comment]
The scripts are really intended to just be examples and are therefore minimalistic.  They'd need optimizing for your own environment.  The other script is even hardwired to localhost:8081 which is also not appropriate for production.
