### ISSUE TITLE
gradle2 examples for publish does not work with artifactory out of the box

### ISSUE THREAD

**Issue by RichardHightower** [JFrogDev/project-examples#16]
https://github.com/JFrogDev/project-examples/tree/master/gradle-examples/gradle2-example-publish

Suggestion: Test your tutorials on a naked box with clean install of gradle and artifactory. There are many missing steps. 

Example should be simpler and should work with artifactory out of the box. More comments. Should not have to configure repos in artifactory server to get "Getting Started" example to work. Perhaps a README that tells you how to setup the missing repos and missing properties that the plugin needs. 

The default does not have a gradle-libs-snapshot repo which the example requires. There is no readme to tell you to create it.

2nd you have create missing repos and disable the POM validation or it does not work. Where is that documented in the example? No where.

3rd the properties are not read for the plugin from the gradle.properites. You have to hard code them or add them to ~/.gradle/gradle.properties.

4th be clear about gradle 1 pub example not for gradle 2.

Also I wasted quite a bit of time trying to get the gradle 1 example to work. There should be a README since there are two explaining, that if you are using gradle 2, don't bother with this go to the other.

**Comment by jbaruch** [comment]
Thanks for the great report! We are on it.

**Comment by shanilevy** [comment]
Thanls for your feedback.
We made all examples compatible with both Gradle 1 and Gradle 2, so that there's no need for different examples for each version.
We also made the examples compatible with the out of the box repository configuration of Artifactory.

**Comment by eyalbe4** [comment]
@RichardHightower , Can we close this issue?

**Comment by RichardHightower** [comment]
sure
