### ISSUE TITLE
Need simple as possible gradle publish example

### ISSUE THREAD

**Issue by RichardHightower** [JFrogDev/project-examples#17]
There needs to be a simple as possible example that works out of the box with artifactory.

Not multi-project. One project to publish. Small as possible. 

The example script seems like it adds a lot of extra gak and sort of detracts from focusing on how to use the artifactory plugin in more of a getting started sort of way. 

I have a jar. I want to publish it to artifactory. Period. 

Also the example does not use the maven plugin so the pom's cannot be validated so they do not work with the libs-snapshot repo. 

This example should only use the repos that come with artifcatory.

**Comment by shanilevy** [comment]
We will soon add a minimal example as you suggested. Thank you.

**Comment by eyalbe4** [comment]
Following this request, we added the "gradle-example-minimal" sample project.
Thanks for your feedback.

**Comment by epylar** [comment]
Could you add a gradle wrapper jar to gradle-example-minimal?

**Comment by eyalbe4** [comment]
@epylar ,
Running "gradle wrapper" will download the gradle-wrapper.jar for you.
We'll make sure we add this to the examples readme file.

**Comment by eyalbe4** [comment]
Contrary to my previous message, in order to allow you to run "./gradlew artifactoryPublish" right after checking out the code, we added the gradle directory to the examples projects.
Thank you for this @epylar !
