### ISSUE TITLE
The example gradle-examples/gradle-example-ci-server is missing the gradle-wrapper.jar

### ISSUE THREAD

**Issue by carstenlenz** [JFrogDev/project-examples#19]
It actually missing the whole 'gradle' folder in 'gradle-examples/gradle-example-ci-server'

**Comment by eyalbe4** [comment]
This specific example should be used with an Artifactory CI Server Plugin (Jenkins, Bamboo or TeamCity). Unlike the other examples in this folder, this one should not be built from the command line, but via the CI Server UI.

**Comment by carstenlenz** [comment]
Yes. But it still needs Gradle to execute. And it is considered best practice to always use the Gradle wrapper for this - also on the CI server. This is why every CI server has the option "use Gradle wrapper". If you don't supply a wrapper you have to install a specific Gradle version on the CI server which you normally should avoid.

**Comment by eyalbe4** [comment]
OK. We'll add it soon. Thanks @carstenlenz .

**Comment by carstenlenz** [comment]
Thanks for your support @eyalbe4 !

**Comment by eyalbe4** [comment]
The 'gradle' folder has been added to the 'gradle-examples/gradle-example-ci-server' project.
