### ISSUE TITLE
Android samples use old gradle plugins, updating breaks samples

### ISSUE THREAD

**Issue by remydavid** [JFrogDev/project-examples#28]
This sample :
https://github.com/JFrogDev/project-examples/blob/master/gradle-examples/4/gradle-android-aar/build.gradle

Uses : 
'com.android.tools.build:gradle:0.9.2'
'com.github.dcendents:android-maven-plugin:1.0'

Android gradle plugin v0.9.2 is very old and not compatible with the latest Android Studio versions, current is 1.5.0.
Also, android-maven-plugin latest version is 1.3.
Updating one or the other breaks the sample.

**Comment by eyalbe4** [comment]
Thanks you for this @remydavid.
Would you be able to contribute and submit a pull request with these changes?

**Comment by noamtamim** [comment]
+1
Please update the sample. I can't get it to work.

**Comment by Manabu-GT** [comment]
@noamtamim you can look at https://github.com/Manabu-GT/project-examples/commit/e44d967561d522cc92591e8d854c9b781f211a3b if you are still having the issue to make it work.

**Comment by eyalbe4** [comment]
@Manabu-GT 's pull request was merged. Thanks @Manabu-GT !
