### ISSUE TITLE
DSL for "Deploy artifacts to Artifactory" post-build action

### ISSUE THREAD

**Issue by kumlali** [JFrogDev/project-examples#46]
[Neither an example](https://github.com/JFrogDev/project-examples/tree/master/jenkins-pipeline-examples) nor a [documentation ](https://wiki.jenkins-ci.org/display/JENKINS/Working+With+the+Pipeline+Jenkins+Plugin) exists on how "Deploy artifacts to Artifactory" post-build action features can be used via Artifactory DSL in Jenkins pipeline script. It is not clear, for example, how
* artifacts can be deployed using Maven repository layout as in "Deploy maven artifacts" feature 
* "Discard old builds from Artifactory" feature can be used
* "Capture and publish build info" feature can be used

**Comment by eyalbe4** [comment]
Hi @kumlali,
Pipeline Artifactory DSL was introduced for the first time in version 2.5.0 of the Jenkins Artifactory Plugin, which was released last week. This release includes only generic upload and download capabilities. We're planning to release Maven and Gradle support, hopefully as part of the next release of the plugin.

**Comment by kumlali** [comment]
Hi @eyalbe4,

Great news! Meanwhile, adding your explanation to [documentation](https://wiki.jenkins-ci.org/display/JENKINS/Working+With+the+Pipeline+Jenkins+Plugin) would save others' time.

**Comment by eyalbe4** [comment]
Thanks for the feedback @kumlali. We've just added this to the Introduction section. We'd appreciate any additional feedback you may have.

**Comment by kumlali** [comment]
I had already read Introduction but was not clear to me. May be I am the only one who do not percieve at first sight. I wanted to give feedback as your contribution to Jenkins ecosystem is valuable.

**Comment by eyalbe4** [comment]
@kumlali, we added this to the Introduction section following your feedback. Thanks again for providing it. With your permission, I'm closing this issue.

**Comment by kumlali** [comment]
Documentation page, somehow, seemed unchanged. After I hit Ctrl+F5, I was able to see your update. Thank you.
