### ISSUE TITLE
NO published modules

### ISSUE THREAD

**Issue by carlolf** [JFrogDev/project-examples#51]
I tried to publish some artifacts from the Gradle build, using your examples from 4. The task artifactoryPublish succeeds, but it only uploads a build info, no built artifacts. This is curious, because my build script says `publishBuildInfo = false`, whereas it explicitely states `publishConfigs('archives')
         publishArtifacts = true`.

I'm using Gradle 3.1, and script code is; 

`apply plugin: 'com.jfrog.artifactory'
apply plugin: 'maven-publish'

publishing {
   publications {
      mavenJava(MavenPublication) {
         pom.withXml {
            asNode().appendNode('description', 'A demonstration of Maven POM customization')
        }
        from components.java
        artifact sourceJar {
            classifier 'sources'
        }  
      }
   }
}
artifactory {  
   contextUrl = artifactoryUrl
   publish {  
      repository {
         repoKey = 'libs-uvdms'
         username = 'xxxx'
         password = 'yyyy'
      }
      defaults {  
         publications('mavenJava')
         publishConfigs('archives')
         publishArtifacts = true  
         publishPom = true 
         publishBuildInfo = false // true by default
      }  
   }  
}  
`

**Comment by eyalbe4** [comment]
@carlolf, the issue that you're experiencing has the same root cause as in:
https://github.com/JFrogDev/build-info/issues/99

We included a snapshot version with a Gradle 3.x compatibility fix that you can use in the meantime. It is included in the above issue. Please try it out. The fix will be of course included as part of the next release.

**Comment by romangurevitch** [comment]
@carlolf, Artifactory gradle plugin version that fixes the issue was released, release version 4.4.6.

**Comment by carlolf** [comment]
Ah, this is very nice! I will try it tomorrow in office. Thanks!

**Comment by carlolf** [comment]
I'm sorry, it still doesn't work for me. As before, task artifactoryPublish just uploads a (unwanted!) build info.

The build did download the new version and logged this:
`Download https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor-gradle/4.4.7/build-info-extractor-gradle-4.4.7.jar
Download https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-extractor/2.6.3/build-info-extractor-2.6.3.jar
Download https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-client/2.6.3/build-info-client-2.6.3.jar
Download https://jcenter.bintray.com/org/jfrog/buildinfo/build-info-api/2.6.3/build-info-api-2.6.3.jar

(...)
:de.uvdms.util:artifactoryPublish
Deploying build descriptor to: http://ourdomain/artifactory/api/build
Build successfully deployed. Browse it in Artifactory under http://ourdomain/artifactory/webapp/builds/uvdms/1476086375442
`

**Comment by romangurevitch** [comment]
@carlolf, I couldn't reproduce the issue based on the info you provided, could you run [gradle-example-minimal](https://github.com/JFrogDev/project-examples/tree/master/gradle-examples/4/gradle-example-minimal)? it is the closes example to the one you provided.

**Comment by carlolf** [comment]
Hi Roman,

just tried the minimal example, and this works! Seems I have to figure out
what's wrong with my own Gradle scripts.
Thanks

Carlo

2016-10-10 15:03 GMT+02:00 Roman Gurevitch <notifications@github.com>:
