### ISSUE TITLE
DSL for "Deploy artifacts to Artifactory" post-build action

### ISSUE THREAD

**Issue by idletekz** [JFrogDev/project-examples#57]
Is there a pipeline DSL method for "Deploy artifacts to Artifactory" with maven build on version 2.7.2? I see that we can <a href=https://github.com/JFrogDev/project-examples/blob/master/jenkins-pipeline-examples/maven-example/Jenkinsfile>build and publish build info</a>, but there doesn't seem to be a way to deploy the artifact using the artifactoryMaven.deployer information.

Is this currently available in the plugin for pipeline or is the uploadSpec the only method available at the moment?

**Comment by romangurevitch** [comment]
@idletekz,
In this [example](https://github.com/JFrogDev/project-examples/blob/master/jenkins-pipeline-examples/maven-example/Jenkinsfile) you can see we are setting the deployer settings that include:
releaseRepo, snapshotRepo and Artifactory server.

By executing the 'run' command with 'clean install' goal you are building and publishing the artifacts to Artifactory according to the above settings.
All the build information is stored in the buildInfo variable that later published as well to Artifactory.

**Comment by idletekz** [comment]
@romangurevitch ahh didnt' realize it was build into maven run dsl. i took a closer look @ the build log and it was skipping deployment due to include/exclude pattern. I updated the pattern per <a href=https://wiki.jenkins-ci.org/display/JENKINS/Artifactory+-+Working+With+the+Pipeline+Jenkins+Plugin#Artifactory-WorkingWiththePipelineJenkinsPlugin-UsingtheArtifactoryDSL>wiki</a> and now it's working. ty for quick reply.
