### ISSUE TITLE
Pipeline script seems to be using the Artifactory Resolver Credentials instead of the Default Deployer Credentials

### ISSUE THREAD

**Issue by idletekz** [JFrogDev/project-examples#58]
When initializing pipeline server using sever id with both deployer and resolver credential, artifactory maven build is always using the resolver credential to deploy.

def server = Artifactory.server('my-server-id')

How can pipeline be configure to use resolver credential to download and deployer credential to deploy?

**Comment by eyalbe4** [comment]
Hi @idletekz,
The server object returned by *Artifactory.server('my-server-id')* and also by *Artifactory.newServer(...)* does not include deployer credentials and resolver credentials. It includes only one pair *username* and *password*. For Maven or Gradle builds, when you wish to use a different Artifactory user for resolution and deployment, it is best to create two server instances, with the relevant credentials.
For example:
```
// Create two server instances:
def resoverServer = Artifactory.server('my-server-id')
def deployerServer = Artifactory.server('my-server-id')
// Set credentials for the two servers:
resoverServer.username = 'resolverUser'
resoverServer.password = 'xxx'
deployerServer.username = 'deployerUser'
deployerServer.password = 'xxx'
// Set the resoverServer and deployerServer on the resolver and deployer respectively:
rtMaven.resolver releaseRepo:'libs-release', snapshotRepo:'libs-snapshot', server: resoverServer
rtMaven.deployer releaseRepo:'libs-release-local', snapshotRepo:'libs-snapshot-local', server: deployerServer
```

By default, the server returned by Artifactory.server('my-server-id') has the default resolver credentials set as *username* and *password*. 
We'll try to improve the Artifactory Pipeline DSL documentation to reflect the above. Please let us know if this helps.

**Comment by idletekz** [comment]
gotcha, thanks.
