### ISSUE TITLE
Cannot find server id

### ISSUE THREAD

**Issue by vrolijken** [JFrogDev/project-examples#59]
Your documentation states 

> If your Artifactory server is already defined in Jenkins, you only need its server ID which can be obtained  under Manage | Configure System

If I look there I find a page like the image in 

https://wiki.jenkins-ci.org/display/JENKINS/Artifactory+Plugin#ArtifactoryPlugin-ArtifactoryPluginConfiguration

I cannot find an id there anywhere. How can I find the id?

**Comment by eyalbe4** [comment]
Hi @vrolijken,
It could be you're using an old version of the Artifactory Plugin (probably older than 2.5.0, in which the server ID was added). Please try upgrading to the latest version.

**Comment by vrolijken** [comment]
\o/   That worked! Thanks. Maybe update the wiki above as well? The screenshot in it looks like mine did, while the text mentions the server id, the pictures don't show it.
