### ISSUE TITLE
upload spec match multiple file extensions

### ISSUE THREAD

**Issue by mr-git** [JFrogDev/project-examples#61]
```
def uploadSpec = '''{
    "files": [
      {
      "pattern": "gitrepo/<project>-(.*)/target/(.*)-'''+version+'''(.*)(.jar|.pom)",
      "target": "snapshots/<organization>/{2}/'''+version+'''/",
      "props": "GitCommitId='''+gitRev+'''",
      "regexp": "true"
      }
   ]
}'''
```
Above is the `uploadSpec` I try to use to upload all `.jar` files and `.pom` files, but Jenkins reports that the pattern matched only `.jar` files.
Is there a way to define such `OR` in pattern? Nowhere in samples I find anything like this.

**Comment by eyalbe4** [comment]
@mr-git, thanks a lot for reporting this issue.
We opened [HAP-854](https://www.jfrog.com/jira/browse/HAP-854) to track this task. Version 1.8.2 of the Jenkins Artifactory Plugin will soon be released and will include the fix.

**Comment by eyalbe4** [comment]
@@mr-git, 2.8.2 is released.
Please let us know if it resolves the issue for you.

**Comment by mr-git** [comment]
Works like expected.
Thanks!

**Comment by eyalbe4** [comment]
Thanks @mr-git.
I'm closing this issue.
