### ISSUE TITLE
Please add license if applicable

### ISSUE THREAD

**Issue by CodingSpiderFox** [JFrogDev/project-examples#65]
Hello,

thanks for the helpful examples. 

However, I was wondering which license is to apply?
I found the Apache license in this file: https://github.com/JFrogDev/project-examples/blob/master/gradle-examples/3/gradle-example/services/webservice/src/main/java/org/gradle/webservice/TestTest.java

Is the whole repository under Apache license? 

If so, maybe it would be helpful to add a LICENSE file to the root of the repo to clarify this.

Thanks in advance!

**Comment by eyalbe4** [comment]
Thanks for letting us know the license is missing @CodingSpiderFox.
This repository is under the Apache 2.0 license. We've just added the license file.

**Comment by CodingSpiderFox** [comment]
Thanks!
