### ISSUE TITLE
Building on Jenkins fails due to updatePolicy

### ISSUE THREAD

**Issue by CodingSpiderFox** [JFrogDev/project-examples#66]
I'm trying to build the maven example with the Artifactory plugin on Jenkins.
My Jenkinsfile looks like this:

`node("builder") {
    def server = Artifactory.server 'Artifactory'
    def rtMaven = Artifactory.newMavenBuild()

    stage 'Build'
        git url: 'https://github.com/jfrogdev/project-examples.git'

    stage 'Artifactory configuration'
        rtMaven.tool = 'maven-default' // Tool name from Jenkins configuration
        rtMaven.deployer releaseRepo:'libs-release-local', snapshotRepo:'libs-snapshot-local', server: server
        rtMaven.resolver releaseRepo:'libs-release', snapshotRepo:'libs-snapshot', server: server
        def buildInfo = Artifactory.newBuildInfo()
        

    stage 'Exec Maven'
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install', buildInfo: buildInfo

    stage 'Publish build info'
        server.publishBuildInfo buildInfo
}`

The error message I get is the following: 

> [main] ERROR org.apache.maven.cli.MavenCli - Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Failure to find org.apache.maven.plugins:maven-plugins:pom:22 in <url>/artifactory/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of artifactory-release has elapsed or updates are forced

If I wait some time (like 2 minutes), the jobs succeeds.

What I actually expected was that it would always update the dependencies.
I think the updatePolicy is not set like I want it to.

Where can I set it?

Does the Maven tool adapter actually use my Jenkins managed global settings.xml for maven by default?

**Comment by CodingSpiderFox** [comment]
Works now.

I think I was either missing a command line option which tells it to always update the dependencies or something in the pom.xml or global maven config was wrong.

Can't remember for sure. Too long ago.

**Comment by jakethedev** [comment]
https://xkcd.com/979/
