### ISSUE TITLE
Maven deploy only after tests were successful

### ISSUE THREAD

**Issue by CodingSpiderFox** [JFrogDev/project-examples#70]
I want to use the Artifactory plugin in my Jenkins pipeline. However, I don't want to publish the artifacts if the tests were not successful.
Here is how I do it at the moment (set the deployArtifacts option to false, Build, Test, set it to true, build again).
Is there any way to avoid having to build it again?

```
def server = Artifactory.server('Artifactory')
def rtMaven = Artifactory.newMavenBuild()
rtMaven.resolver server: server, releaseRepo: 'maven-resolver', snapshotRepo: 'maven-snapshot'
rtMaven.deployer server: server, releaseRepo: 'maven', snapshotRepo: 'maven-snapshot'
rtMaven.deployer.deployArtifacts = false
rtMaven.tool = 'maven-default'
def buildInfo = null;

stage('Checkout') {
    step([$class: 'WsCleanup'])
    checkout scm
}

stage('Build with Artifactory') {
    buildInfo = rtMaven.run pom: 'pom.xml', goals: 'clean compile test-compile install --update-snapshots -DskipTests=true', buildInfo: buildInfo;
}

stage('Test') {
    buildInfo = rtMaven.run pom: 'pom.xml', goals: 'initialize surefire:test', buildInfo: buildInfo;
    junit '**/target/surefire-reports/*.xml'
}

stage('Deploy Artifactory') {
    rtMaven.deployer.deployArtifacts = true
    buildInfo = rtMaven.run pom: 'pom.xml', goals: 'clean compile install -DskipTests=true', buildInfo: buildInfo;
    server.publishBuildInfo buildInfo
}
```

**Comment by trisquel87** [comment]
Hi @CodingSpiderFox , can you use exceptions, your code can be similar to this:

`def server = Artifactory.server('Artifactory')
def rtMaven = Artifactory.newMavenBuild()
rtMaven.resolver server: server, releaseRepo: 'maven-resolver', snapshotRepo: 'maven-snapshot'
rtMaven.deployer server: server, releaseRepo: 'maven', snapshotRepo: 'maven-snapshot'
rtMaven.deployer.deployArtifacts = false
rtMaven.tool = 'maven-default'
def buildInfo = null;

try {

	stage('Checkout') {
		//Your code
	}

	stage('Build with Artifactory') {
		//Your code
	}

	stage('Test') {
		//Your code
	}

	stage('Deploy Artifactory') {
		//Your code
	}

}catch (caughtError) {
	//Set the currentBuild result to  "FAILURE"
	echo "${caughtError}"
}`

If your Jenkins pipeline launch an exception, your 'Deploy Artifactory' stage don't will be launch. Can you try it?

**Comment by CodingSpiderFox** [comment]
Yes, it works now. Thanks.

**Comment by liuxh0** [comment]
Hi @CodingSpiderFox ,

can you tell me how did you solve the problem? I have a similar need. 

I think if the test stages fails, the deployment stage will not be executed, right?
