### ISSUE TITLE
gradle-examples/4/gradle-example needs newer gradle-wrapper, 2.0 fails

### ISSUE THREAD

**Issue by javabrett** [JFrogDev/project-examples#95]
This project declares a very old Gradle (2.0) in its wrapper and does not work:

```
* What went wrong:
Failed to notify build listener.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
> Could not find method getPluginManager() for arguments [] on root project 'gradle-example'.
```

Should upgrade to latest Gradle 4.3.1.

Build failure in Travis: https://travis-ci.org/javabrett/project-examples/builds/306531512
Improved build failure in Travis (resolves this issue), exposes new issue: https://travis-ci.org/javabrett/project-examples/builds/306532953

**Comment by eyalbe4** [comment]
Thanks for submitting the pull request @javabrett.
We'll probably need to upgrade the gradle version in all gradle examples in this repository.

**Comment by javabrett** [comment]
> We'll probably need to upgrade the gradle version in all gradle examples in this repository.

Right, but since they are not linked, I figured I'd make a start with this one, especially since it does not currently build as-is.
